# Generated by Django 5.0.4 on 2024-06-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "phone_number",
                    models.CharField(default="", max_length=15, unique=True),
                ),
                ("email", models.EmailField(default="", max_length=100, unique=True)),
                ("date_of_birth", models.DateField(max_length=15, null=True)),
                ("gender", models.CharField(default="", max_length=12)),
                ("doctor_name", models.CharField(default="", max_length=100)),
                ("specialization", models.CharField(default="", max_length=12)),
                ("location", models.CharField(default="", max_length=12)),
                ("date", models.CharField(default="", max_length=12)),
                ("appointed_date", models.CharField(default="", max_length=12)),
                ("payment", models.CharField(max_length=12)),
            ],
        ),
    ]
