# Generated by Django 5.0.4 on 2024-06-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patientbooking", "0002_alter_patient_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="appointed_date",
            field=models.CharField(default="", max_length=120),
        ),
    ]
