# Generated by Django 4.0.6 on 2024-06-07 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(default='', max_length=15, unique=True)),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
                ('date_of_birth', models.DateField(max_length=15, null=True)),
                ('gender', models.CharField(default='', max_length=12)),
                ('specialization', models.CharField(default='', max_length=120)),
                ('location', models.CharField(default='', max_length=120)),
                ('dates', models.DateField(default='', max_length=12)),
                ('appointed_date', models.CharField(default='', max_length=12)),
                ('payment', models.CharField(max_length=12)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
