# Generated by Django 4.0.6 on 2024-06-07 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=15, null=True)),
                ('from_time', models.CharField(max_length=15, null=True)),
                ('to_time', models.CharField(max_length=15, null=True)),
                ('location', models.CharField(max_length=15, null=True)),
                ('availability', models.CharField(max_length=15, null=True)),
                ('deptId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='department.department')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
