# Generated by Django 5.0.4 on 2024-06-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userauthentication",
            name="last_login",
            field=models.DateTimeField(default="", null=True),
        ),
    ]
