# Generated by Django 5.0.3 on 2024-05-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=100, null=True)),
                ("department_no", models.CharField(max_length=100, null=True)),
                ("department_head", models.CharField(max_length=100, null=True)),
                ("department_date", models.DateField(max_length=15, null=True)),
                (
                    "department_status",
                    models.CharField(default="Active", max_length=100),
                ),
                ("department_info", models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
